sky:
  datasource: 
    driver-class-name: oracle.jdbc.OracleDriver
    host: localhost
    port: 1521
    database: orcl
    username: sky
    password: 123456
     
  alioss: 
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: xxxxxxxxxxxx
    access-key-secret: xxxxxxxxxxxx
    bucket-name: sky-mybucket-takeout
  
  #配置redis数据源
  redis: 
    home: localhost
    password: 123456
    port: 6379
    database: 0